const anecdotes = [
  "Les kiwis ne volent pas, mais ils ont des narines au bout du bec.",
  "Le chocolat était utilisé comme monnaie chez les Mayas.",
  "La Lune s’éloigne de la Terre de 3,8 cm par an.",
  "Les pieuvres ont trois cœurs et du sang bleu.",
  "Un éclair chauffe l’air à 30 000°C, cinq fois plus que la surface du Soleil.",
  "Les girafes dorment moins de 2 heures par jour.",
  "Le cœur d’une crevette est situé dans sa tête.",
  "Les bananes sont des baies, mais les fraises non.",
  "Le miel ne périme jamais : on a retrouvé du miel comestible vieux de 3000 ans.",
  "Les escargots peuvent dormir pendant trois ans.",
  "Napoléon a été attaqué par des lapins lors d’une chasse organisée.",
  "Cléopâtre a vécu plus près de l’invention de l’iPhone que de la construction des pyramides.",
  "Le drapeau du Danemark est le plus ancien encore utilisé aujourd’hui (depuis 1219).",
  "En 1518, une épidémie de danse a frappé Strasbourg : des gens ont dansé jusqu’à l’épuisement.",
  "La Tour Eiffel peut grandir de 15 cm en été à cause de la chaleur.",
  "Le Titanic transportait 3 tonnes de mayonnaise.",
  "Le premier réveil ne pouvait sonner qu’à 4h du matin.",
  "En 1952, Londres a été paralysée par un brouillard toxique pendant 5 jours.",
  "Mozart a commencé à composer à 5 ans.",
  "Léonard de Vinci écrivait de la main gauche… et en miroir.",
  "Le mot “robot” vient du tchèque “robota” qui signifie “travail forcé”.",
  "Le premier email a été envoyé en 1971.",
  "Le smiley 🙂 a été inventé en 1982 par un informaticien américain.",
  "Le premier jeu vidéo commercial s’appelait “Pong” (1972).",
  "Le mot “ordinateur” vient du latin “ordinare” (mettre en ordre).",
  "Les étoiles de mer n’ont pas de cerveau.",
  "Les requins existent depuis plus de 400 millions d’années.",
  "Les girafes n’ont pas de cordes vocales.",
  "Les fourmis n’ont pas de poumons.",
  "Le plus long vol d’un poulet a duré 13 secondes.",
  "Les crocodiles ne peuvent pas tirer la langue.",
  "Le plus petit os du corps humain est dans l’oreille.",
  "Les vaches ont des meilleurs amis et sont stressées quand elles sont séparées.",
  "Le mot 'alphabet' vient des deux premières lettres grecques : alpha et bêta.",
  "Les astronautes ne peuvent pas pleurer dans l’espace : les larmes ne coulent pas.",
  "Le premier ordinateur pesait plus de 27 tonnes.",
  "Les flamants roses sont blancs à la naissance.",
  "Le mot 'sabotage' vient des sabots que les ouvriers jetaient dans les machines.",
  "Le plus vieux chewing-gum date de 9000 ans.",
  "Les dauphins dorment avec un œil ouvert.",
  "Le nom Google vient d’une faute de frappe sur le mot 'googol'.",
  "Les pandas passent environ 12 heures par jour à manger.",
  "La barbe pousse plus vite quand on pense au sexe.",
  "Les fourmis peuvent survivre dans un micro-ondes.",
  "Le mot 'testicule' vient du latin 'testis', qui signifie témoin.",
  "Les tortues peuvent respirer par leurs fesses.",
  "Le plus long mot français sans voyelle est 'myrth' (ancien).",
  "Les abeilles peuvent reconnaître les visages humains.",
  "Le plus vieux message dans une bouteille a mis 108 ans à être retrouvé.",
  "Les koalas ont des empreintes digitales presque identiques à celles des humains.",
  "Le mot 'clavier' vient du latin 'clavis' qui signifie clé.",
  "Les requins sont immunisés contre presque toutes les maladies.",
  "Le premier SMS envoyé disait 'Merry Christmas'.",
  "Les méduses n’ont ni cerveau, ni cœur, ni os.",
  "Le plus grand organisme vivant est un champignon souterrain dans l’Oregon.",
  "Les chats peuvent faire plus de 100 sons différents, les chiens moins de 10.",
  "Les Vikings utilisaient des os de baleine pour fabriquer des skis.",
  "Le mot 'ordinateur' n’existait pas avant 1955.",
  "Les grenouilles avalent avec les yeux : elles les rentrent pour pousser la nourriture.",
  "La mer Morte est le point le plus bas de la surface terrestre : 429 mètres sous le niveau de la mer.",
  "Le Canada possède plus de lacs que tous les autres pays réunis.",
  "Il existe un village en Norvège nommé Hell, avec une gare appelée 'Hell Station'.",
  "Le désert du Sahara a vu de la neige en 1979 et en 2018.",
  "Le lac Retba au Sénégal est naturellement rose à cause de bactéries halophiles.",
  "La Russie s’étend sur 11 fuseaux horaires.",
  "Le Nil est plus long que l’Amazone, mais l’Amazone transporte plus d’eau.",
  "Le mont Everest grandit de quelques millimètres chaque année.",
  "La ville de Rome a plus de fontaines que n’importe quelle autre ville au monde.",
  "Le Groenland est géographiquement en Amérique du Nord mais politiquement lié à l’Europe.",
  "Cléopâtre parlait au moins neuf langues.",
  "Le roi Charles VI de France croyait qu’il était fait de verre.",
  "Tsutomu Yamaguchi a survécu aux deux bombes atomiques : Hiroshima et Nagasaki.",
  "Le mot 'OK' viendrait de l’expression 'Oll Korrect', une blague orthographique du XIXe siècle.",
  "En 1835, un imposteur a convaincu des Britanniques d’investir dans un pays imaginaire appelé 'Poyais'.",
  "Le président américain Andrew Jackson a tué son adversaire lors d’un duel… après avoir été blessé.",
  "Le calendrier maya ne prédisait pas la fin du monde en 2012, mais le début d’un nouveau cycle.",
  "La Tour de Pise penche à cause d’un sol trop meuble, pas à cause de sa construction.",
  "Le Titanic avait un jumeau presque identique : le Britannic, qui a aussi coulé.",
  "Le mur de Berlin a été construit en une nuit, le 13 août 1961.",
  "Il existe une ville en Alaska appelée Chicken, car les fondateurs ne savaient pas écrire 'ptarmigan'.",
  "En Australie, il y a un lac qui devient rose bonbon à certaines périodes : le lac Hillier.",
  "La ville de Dubaï a construit une piste de ski en intérieur… en plein désert.",
  "Il existe un village en Inde où les maisons sont décorées avec des coquilles d’œufs.",
  "En Écosse, le village de Dull est jumelé avec Boring (Oregon) et Bland (Australie).",
    "Le roi Ludwig II de Bavière a construit des châteaux féeriques… et a fini interné pour folie.",
  "Ivan le Terrible a tué son propre fils dans un accès de rage.",
  "La reine Juana d’Espagne gardait le corps de son mari dans un cercueil qu’elle emmenait partout.",
  "Charles II d’Espagne était si consanguin qu’il ne pouvait ni parler ni marcher correctement.",
  "Le roi Zog d’Albanie fumait 200 cigarettes par jour et a survécu à plus de 50 tentatives d’assassinat.",
  "Le micro-ondes a été inventé par accident quand un radar a fait fondre une barre chocolatée.",
  "Le stéthoscope a été inventé par un médecin trop pudique pour coller son oreille sur une patiente.",
  "Le Velcro a été inspiré par des graines accrochées aux vêtements lors d’une randonnée.",
  "Le Coca-Cola était à l’origine vendu comme médicament contre les maux de tête.",
  "La pénicilline a été découverte grâce à une moisissure oubliée dans une boîte de Petri.",
  "Le Segway était censé révolutionner la mobilité… mais a surtout servi aux visites guidées.",
  "Le parachute a été testé pour la première fois par un homme sautant de la Tour Eiffel… il n’a pas survécu.",
  "Le Titanic était présenté comme insubmersible… il a coulé lors de son premier voyage.",
  "La machine à prédire les tremblements de terre de 1890 n’a jamais fonctionné.",
  "Le casque anti-bombes de la Seconde Guerre mondiale ressemblait à une boîte de conserve géante.",
  "Le philosophe Chrysippe serait mort de rire après avoir vu un âne manger des figues.",
  "Le roi Adolf Frederick de Suède est mort d’indigestion après un repas de 14 plats… dont du dessert à la semoule.",
  "Le danseur Isadora Duncan est morte étranglée par son écharpe prise dans la roue d’une voiture.",
  "En 1923, un jockey a gagné une course… mort depuis plusieurs minutes sur son cheval.",
  "Le poète Aeschylus serait mort après qu’un vautour a lâché une tortue sur sa tête, pensant que son crâne était un rocher.",
    "Appeler un chat un chat vient du XVIe siècle et signifie dire les choses franchement.",
  "Être sur son 31 viendrait du luxe des tissus vendus par la maison 'Trente-et-un' à Paris.",
  "Tomber dans les pommes vient d’une vieille expression : 'tomber dans les pâmes', qui signifiait s’évanouir.",
  "Avoir le cafard vient du poète Baudelaire, qui associait ce mot à la mélancolie.",
  "Poser un lapin signifiait à l’origine ne pas payer une prostituée… puis a évolué vers 'ne pas venir à un rendez-vous'.",
    "L’homme aux plus longs poils d’oreille mesurait 18,1 cm (Inde, Guinness 2023).",
  "Le plus jeune DJ de club avait 4 ans et 130 jours (Hong Kong, 2019).",
  "Une vache nommée Blosom mesurait 1,90 m, la plus grande jamais enregistrée.",
  "Le plus long rot humain a duré 18 secondes.",
  "Le record du plus grand nombre de cuillères sur un corps humain est de 50.",
    "Aphrodite est née des parties génitales d’Ouranos tombées dans la mer.",
  "Zeus a été élevé par une chèvre pour échapper à son père Cronos.",
  "Le mot 'narcissique' vient de Narcisse, tombé amoureux de son propre reflet.",
  "Sisyphe a été condamné à pousser un rocher éternellement pour avoir défié les dieux.",
  "Prométhée a volé le feu aux dieux pour le donner aux humains, et fut enchaîné à un rocher.",
    "Le mot 'poubelle' vient du préfet Eugène Poubelle, qui imposa les bacs à déchets en 1883.",
  "Napoléon a été attaqué par des lapins lors d’une chasse qu’il avait lui-même organisée.",
  "Le roi Henri VIII d’Angleterre a eu six épouses, dont deux décapitées.",
  "En 1835, un imposteur a inventé un pays fictif, 'Poyais', et vendu des terres à des Britanniques.",
  "Le président américain Andrew Jackson a tué son adversaire en duel… après avoir été blessé.",
  "Le calendrier maya ne prédisait pas la fin du monde en 2012, mais le début d’un nouveau cycle.",
  "Le Titanic transportait 3 tonnes de mayonnaise pour ses cuisines.",
  "Le roi Zog d’Albanie a survécu à plus de 50 tentatives d’assassinat.",
  "Le philosophe Chrysippe serait mort de rire en voyant un âne manger des figues.",
  "Le mot 'robot' vient du tchèque 'robota', qui signifie 'travail forcé'.",
    "Aphrodite est née des parties génitales d’Ouranos tombées dans la mer.",
  "Zeus a été élevé par une chèvre pour échapper à son père Cronos.",
  "Sisyphe est condamné à pousser un rocher éternellement pour avoir défié les dieux.",
  "Prométhée a volé le feu aux dieux pour le donner aux humains, et fut enchaîné à un rocher.",
  "Le mot 'narcissique' vient de Narcisse, tombé amoureux de son propre reflet.",
  "Athéna est sortie toute armée du crâne de Zeus.",
  "Hermès est le dieu des voleurs, des voyageurs… et des marchands.",
  "Hercule a accompli 12 travaux, dont tuer l’hydre de Lerne et capturer Cerbère.",
  "Hadès n’est pas le diable : il règne sur les morts mais n’est pas maléfique.",
  "Les dieux grecs ont des défauts humains : jalousie, colère, vengeance.",
    "La mer Morte est 429 mètres sous le niveau de la mer, le point le plus bas sur Terre.",
  "Le Canada possède plus de lacs que tous les autres pays réunis.",
  "Le lac Hillier en Australie est naturellement rose bonbon.",
  "La Russie s’étend sur 11 fuseaux horaires.",
  "L’Antarctique est le plus grand désert du monde, malgré sa glace.",
  "Il existe une montagne en Nouvelle-Zélande avec un nom de 85 lettres.",
  "Le Groenland est géographiquement en Amérique mais politiquement lié à l’Europe.",
  "Le Nil est plus long que l’Amazone, mais l’Amazone transporte plus d’eau.",
  "L’Australie est le seul continent sans volcans actifs.",
  "Le mont Everest grandit de quelques millimètres chaque année.",
    "Les crevettes peuvent voir dans 16 types de couleurs, contre seulement 3 pour les humains.",
  "Le mot 'sandwich' vient du comte de Sandwich, qui mangeait entre deux tranches de pain pour continuer à jouer aux cartes.",
  "Les kangourous ne peuvent pas reculer.",
  "Le chewing-gum est interdit à la vente à Singapour depuis 1992.",
  "Le plus long mot français sans voyelle est 'tsktsk'.",
  "Les chats n’ont pas de clavicule, ce qui leur permet de passer dans des trous très étroits.",
  "Le mot 'bikini' vient de l’atoll de Bikini, où ont eu lieu des essais nucléaires.",
  "Les méduses existent depuis plus de 500 millions d’années.",
  "Le mot 'abracadabra' était utilisé comme formule de guérison dans l’Antiquité.",
  "Les autruches peuvent courir plus vite que des chevaux.",
  "Le Coca-Cola serait vert sans colorant.",
  "Les moustiques sont attirés par les gens qui ont mangé des bananes.",
  "Le mot 'barbecue' vient du mot taïno 'barbacoa'.",
  "Les poissons rouges ont une meilleure mémoire qu’on ne le croit : jusqu’à 3 mois.",
  "Le mot 'clown' vient du mot islandais 'klunni', qui signifie maladroit.",
  "Les bébés ont environ 100 os de plus que les adultes.",
  "Le plus long hoquet jamais enregistré a duré 68 ans.",
  "Les éléphants ne peuvent pas sauter.",
  "Le mot 'robot' a été inventé dans une pièce de théâtre tchèque en 1920.",
  "Les cacahuètes ne sont pas des noix, mais des légumineuses.",
  "Le mot 'papier' vient du papyrus, une plante utilisée en Égypte antique.",
  "Les flamants roses deviennent roses à cause des crevettes qu’ils mangent.",
  "Le mot 'safari' vient du swahili et signifie 'voyage'.",
  "Les serpents peuvent dormir les yeux ouverts, car ils n’ont pas de paupières.",
  "Le mot 'galaxie' vient du grec 'galaxias', qui signifie 'lait' (d’où la Voie lactée).",
  "Les fourmis peuvent soulever jusqu’à 50 fois leur poids.",
  "Le mot 'poubelle' vient du nom d’un préfet de Paris, Eugène Poubelle.",
  "Les girafes n’ont que 7 vertèbres cervicales, comme les humains.",
  "Le mot 'trampoline' vient de l’italien 'trampolino', qui signifie tremplin.",
  "Les dauphins ont des noms entre eux et peuvent s’appeler par sifflement.",
    "Le mot 'bonjour' était autrefois réservé aux gens de rang supérieur.",
  "Les manchots ont des genoux, cachés sous leur plumage.",
  "Le plus grand désert du monde n’est pas le Sahara, mais l’Antarctique.",
  "Les licornes sont l’animal national de l’Écosse.",
  "Le mot 'merci' vient du latin 'mercedem', qui signifie récompense.",
  "Les moustaches des chats servent à mesurer les espaces étroits.",
  "Le drapeau du Népal est le seul à ne pas être rectangulaire.",
  "Les grenouilles absorbent l’eau par la peau, pas par la bouche.",
  "Le mot 'bizarre' vient du basque 'bizar', qui signifie barbe.",
  "Les méduses peuvent vivre éternellement… certaines espèces se régénèrent indéfiniment.",
  "Le mot 'panique' vient du dieu Pan, qui effrayait les voyageurs.",
  "Les baleines chantent des chansons qui peuvent durer plusieurs heures.",
  "Le mot 'salaire' vient du sel, qui servait de monnaie.",
  "Les girafes peuvent nettoyer leurs oreilles avec leur langue.",
  "Le plus vieux pantalon du monde date de 3000 ans et vient de Chine.",
  "Les étoiles filantes sont souvent des grains de sable spatiaux.",
  "Le mot 'travail' vient du latin 'tripalium', un instrument de torture.",
  "Les pieuvres peuvent changer de forme pour imiter d’autres animaux.",
  "Le plus petit pays du monde est le Vatican, avec 0,44 km².",
  "Les dauphins ont des noms et se reconnaissent par leurs sifflements.",
  "Le mot 'testament' vient du latin 'testari', qui signifie témoigner.",
  "Les éléphants peuvent pleurer et enterrer leurs morts.",
  "Le mot 'lunatique' vient du lien supposé entre la Lune et les sautes d’humeur.",
  "Les fourmis cultivent des champignons dans leurs colonies.",
  "Le plus long tunnel ferroviaire du monde est en Suisse : le tunnel du Gothard.",
  "Le mot 'maladie' vient de 'mal aise'.",
  "Les requins peuvent vivre plusieurs semaines sans manger.",
  "Le mot 'école' vient du grec 'skholè', qui signifiait loisir.",
  "Les flamants roses dorment sur une seule patte.",
  "Le plus vieux jeu de société connu est le Senet, joué en Égypte il y a 5000 ans.",
  "Les tortues peuvent respirer par leur cloaque (oui, leur derrière).",
  "Le mot 'ordinateur' n’existait pas avant 1955.",
  "Les Vikings utilisaient des os de baleine pour fabriquer des skis.",
  "Le mot 'clavier' vient du latin 'clavis', qui signifie clé.",
  "Le plus vieux message dans une bouteille a mis 108 ans à être retrouvé.",
  "Le mot 'robot' a été inventé dans une pièce de théâtre tchèque en 1920.",
  "Les koalas ont des empreintes digitales presque identiques à celles des humains.",
  "Le mot 'galaxie' vient du grec 'galaxias', qui signifie lait.",
  "Les pandas passent environ 12 heures par jour à manger.",
  "Le mot 'sabotage' vient des sabots jetés dans les machines par les ouvriers.",
    "Le mot 'chaussette' vient du latin 'soccus', une sandale de comédie romaine.",
  "Les hippocampes mâles portent les bébés dans une poche ventrale.",
  "Le grille-pain a été inventé avant le pain tranché.",
  "Le dieu Thor avait une chèvre magique qui se régénérait après avoir été mangée.",
  "Le plus grand nombre de cuillères sur un corps humain est de 50.",
  "Il existe un village en Espagne nommé 'Penas de San Pedro' construit au bord d’une falaise.",
  "En 1815, Napoléon a échappé à l’exil… en volant un bateau.",
  "Le stéthoscope a été inventé par un médecin trop pudique pour poser l’oreille sur une patiente.",
  "Le mot 'bizarre' vient du basque 'bizar', qui signifie barbe.",
  "Les pieuvres ont trois cœurs et du sang bleu.",
  "Le mot 'robot' a été inventé dans une pièce de théâtre tchèque en 1920.",
  "Le roi Charles VI de France croyait qu’il était fait de verre.",
  "Le mot 'safari' vient du swahili et signifie 'voyage'.",
  "Les flamants roses dorment sur une seule patte.",
  "Le plus vieux chewing-gum date de 9000 ans.",
  "Le mot 'travail' vient du latin 'tripalium', un instrument de torture.",
  "Les chats n’ont pas de clavicule, ce qui leur permet de se faufiler partout.",
  "Le mot 'panique' vient du dieu Pan, qui effrayait les voyageurs.",
  "Le plus long tunnel ferroviaire du monde est en Suisse : le tunnel du Gothard.",
  "Le Coca-Cola était à l’origine vendu comme médicament contre les maux de tête.",
  "Le mot 'bonjour' était autrefois réservé aux nobles.",
  "Les dauphins ont des noms entre eux et se reconnaissent par leurs sifflements.",
  "Le mot 'ordinateur' n’existait pas avant 1955.",
  "Le roi Zog d’Albanie fumait 200 cigarettes par jour.",
  "Le mot 'clavier' vient du latin 'clavis', qui signifie clé.",
  "Le plus vieux pantalon du monde date de 3000 ans.",
  "Les fourmis peuvent survivre dans un micro-ondes.",
  "Le mot 'lunatique' vient du lien supposé entre la Lune et les sautes d’humeur.",
  "Le mot 'abracadabra' était utilisé comme formule de guérison dans l’Antiquité.",
  "Les moustiques sont attirés par les gens qui ont mangé des bananes.",
  "Le mot 'merci' vient du latin 'mercedem', qui signifie récompense.",
  "Le mot 'poubelle' vient du préfet Eugène Poubelle.",
  "Les méduses peuvent vivre éternellement… certaines espèces se régénèrent indéfiniment.",
  "Le mot 'alphabet' vient des deux premières lettres grecques : alpha et bêta.",
  "Le mot 'galaxie' vient du grec 'galaxias', qui signifie lait.",
  "Les Vikings utilisaient des os de baleine pour fabriquer des skis.",
  "Le mot 'testicule' vient du latin 'testis', qui signifie témoin.",
  "Le mot 'barbecue' vient du mot taïno 'barbacoa'.",
  "Le mot 'sabotage' vient des sabots jetés dans les machines par les ouvriers.",
  "Le mot 'école' vient du grec 'skholè', qui signifiait loisir.",
    "Johnny Depp souffre de coulrophobie : il a peur des clowns.",
  "Kesha a un QI de 140, bien au-dessus de la moyenne.",
  "Leonardo DiCaprio a été nommé ainsi car sa mère l’a senti bouger en regardant une œuvre de Léonard de Vinci.",
  "Cassius Clay (Mohamed Ali) a commencé la boxe après qu’on lui a volé son vélo à 12 ans.",
  "Albert Einstein ne portait jamais de chaussettes.",
  "Steve Jobs a suivi des cours de calligraphie, ce qui a influencé la typographie du Mac.",
  "Elton John a été sauvé d’une overdose par un ami qui l’a plongé dans de l’eau glacée.",
  "Bill Gates a été arrêté en 1977 pour excès de vitesse sans permis.",
  "Napoléon mesurait environ 1m69, mais était considéré petit à cause d’une confusion d’unités.",
  "Nikola Tesla avait une obsession pour le chiffre 3 et se lavait les mains exactement 3 fois.",
  "Salvador Dalí se promenait avec une cloche pour attirer l’attention.",
  "Winston Churchill s’endormait souvent dans son bain en fumant un cigare.",
  "Lady Gaga a écrit son premier tube 'Just Dance' en 10 minutes.",
  "Barack Obama collectionne les comics de Spider-Man et Conan le Barbare.",
  "Frida Kahlo a survécu à un accident de bus qui l’a laissée avec 32 opérations chirurgicales.",
  "Stephen Hawking est né exactement 300 ans après la mort de Galilée.",
  "Tom Hanks collectionne les vieilles machines à écrire.",
  "Marilyn Monroe possédait plus de 400 livres dans sa bibliothèque personnelle.",
  "Taylor Swift a appris à écrire son nom en cursive avant de savoir lire.",
  "Keanu Reeves a donné une grande partie de son salaire de Matrix à l’équipe technique."
];

document.getElementById("factButton").addEventListener("click", () => {
  const random = anecdotes[Math.floor(Math.random() * anecdotes.length)];
  document.getElementById("factDisplay").textContent = random;
});

document.getElementById("moreButton").addEventListener("click", () => {
  const bubble = document.getElementById("moreBubble");
  bubble.style.display = bubble.style.display === "none" ? "block" : "none";
});